Adding swagger api to notification service
communitiesuk/funding-service-design-notification pull request #14
Opened 2022-07-13 10:09 UTC by ramsharma-prog

2022-08-09 14:16 UTC, SentientHousePlant requested changes

2022-08-09 14:37 UTC, ramsharma-prog commented on app/notification/model/notifier.py
>          except:  # noqa
with if else statement, it doesn't not return the customised error  if the email format is incorrect instead it returns the error from notification service hence I added try except?

2022-08-09 14:46 UTC, SentientHousePlant commented on app/notification/model/notifier.py
>          except:  # noqa
make sure that the except selects a specific error otherwise anything could happen :)

2022-08-09 15:11 UTC, ramsharma-prog commented on app/notification/model/notifier.py
>          except:  # noqa
Done

2022-08-11 12:48 UTC, SentientHousePlant requested changes

2022-08-12 17:39 UTC, ramsharma-prog commented on app/notification/magic_link/map_contents.py
> -)
Now I am returning from_json function from data class (MagicLink) which contains all the required keys, values for Magic link. If any of the values is missing then it returns json with null value including invalid  email. Happy to have a chat?

2022-08-18 13:52 UTC, gidsg commented on app/notification/application/map_contents.py
> +        print(application)
can we remove this debug?

2022-08-18 14:02 UTC, ramsharma-prog commented on app/notification/application/map_contents.py
> +        print(application)
removed

2022-08-18 15:10 UTC, SentientHousePlant approved these changes

2022-08-18 15:57 UTC, gidsg approved these changes

2022-08-18 15:58 UTC, merged